// <auto-generated />
namespace CarRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditedLoans_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedLoans_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206271743286_EditedLoans_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
