// <auto-generated />
namespace CarRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RentalRecordEdited_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RentalRecordEdited_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202207131724106_RentalRecordEdited_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
